
import pandas as pd
import os
import sys
from datetime import date, datetime, timedelta
from dateutil.relativedelta import relativedelta
import time

# Add project root to path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from config import PROCESSED_DATA_DIR, COMMODITY_CONFIG
from collectors.exagri_scraper import get_pepper_scraper

def fetch_and_merge_real_prices():
    """
    Fetch real prices from Exagri for the missing period (June 2024 - Present)
    and merge with the processed dataset.
    """
    # 1. Load the dataset (which might have NaNs or interpolated values from previous steps)
    # We'll rely on the one generated by ingest_pepper (cleaned of NaNs) or just start from known cutoff.
    # Let's load the file that has the 'skeleton' (dates up to 2025) if possible, or build it.
    # Actually, simpler to load the "clean" input from ingest (up to 2024-05) and APPEND new real data.
    
    base_file = os.path.join(PROCESSED_DATA_DIR, 'pepper_prices.csv')
    if not os.path.exists(base_file):
        print("Base file not found.")
        return

    df = pd.read_csv(base_file)
    df['Date'] = pd.to_datetime(df['Date'])
    
    last_date = df['Date'].max()
    print(f"Last data point in file: {last_date.date()}")
    
    # We want to fetch from next month until now
    start_date = last_date + relativedelta(months=1)
    # Use current system date as end point
    end_date = datetime.now()
    
    # Optional: If you want to force it to be start of current month
    end_date = end_date.replace(day=1) 
    
    if start_date >= end_date:
        print("Data is already up to date.")
        return

    print(f"Fetching data from {start_date.date()} to {end_date.date()}...")
    
    scraper = get_pepper_scraper()
    new_rows = []
    
    current = start_date
    while current <= end_date:
        print(f"  Fetching {current.strftime('%Y-%m')}...")
        try:
            prices = scraper.get_monthly_average_prices(current.year, current.month)
            
            if prices:
                # We need to construct rows for each region/grade found
                # We also need values for other columns (Fuel, Exchange, etc.)
                # We will copy the latest known values from the dataframe (forward fill strategy for external factors)
                last_row = df.iloc[-1]
                
                for region, grades in prices.items():
                    for grade, price in grades.items():
                        new_row = last_row.copy()
                        new_row['Date'] = current
                        new_row['Region'] = region
                        new_row['Grade'] = grade
                        new_row['Regional_Price'] = price
                        
                        # Recalculate other fields if needed
                        # Update seasonal impact
                        # Pepper Harvest: Feb-May (2,3,4,5)
                        is_harvest = 1 if current.month in [2, 3, 4, 5] else 0
                        new_row['Vietnam_Harvest_Flag'] = is_harvest
                        new_row['Seasonal_Impact'] = 1 if is_harvest else 0 # Simplified logic
                        
                        # Set National Price (approximate as regional for row structure, or same logic as ingest)
                        # We'll calculate proper national price later or per row
                        new_row['National_Price'] = price # Placeholder, will update later
                        
                        new_rows.append(new_row)
            else:
                print(f"    No data found for {current.strftime('%Y-%m')}")
                
        except Exception as e:
            print(f"    Error fetching: {e}")
        
        current += relativedelta(months=1)
        # small delay to be nice
        time.sleep(1)

    if not new_rows:
        print("No new data fetched.")
        return

    # Create DF from new rows
    new_df = pd.DataFrame(new_rows)
    # Ensure columns match
    new_df = new_df[df.columns]
    
    # Merge
    combined_df = pd.concat([df, new_df], ignore_index=True)
    
    # Recalculate National Price for new rows correctly
    # Group by Date/Grade
    # (We can just do it for the whole DF to be safe)
    national_prices = combined_df.groupby(['Date', 'Grade'])['Regional_Price'].transform('mean')
    combined_df['National_Price'] = national_prices.round(2)
    
    # Sort
    combined_df = combined_df.sort_values(['Date', 'Region', 'Grade'])
    
    # Save
    combined_df.to_csv(base_file, index=False)
    print(f"Updated dataset saved to {base_file}")
    print(f"New total rows: {len(combined_df)}")
    print(combined_df.tail())

if __name__ == "__main__":
    fetch_and_merge_real_prices()
